#!/usr/bin/env python3
"""Rebuild catalog/graph.json + catalog/STATUS.md from every pack's product.json + gates.json.
  python3 tools/build_graph.py"""
import os, json
CAT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))); CFG = json.load(open(f'{CAT}/config.json'))
nodes, edges, rows = [], [], []
for t in CFG['templates']: nodes.append(dict(id=t, type='template'))
for s, v in json.load(open(f'{CAT}/suppliers.json')).items(): nodes.append(dict(id=f'SUP:{s}', type='supplier', name=v['name']))
for d in sorted(os.listdir(f'{CAT}/packs')):
    pk = f'{CAT}/packs/{d}'
    if not os.path.isfile(f'{pk}/product.json'): continue
    P = json.load(open(f'{pk}/product.json')); G = json.load(open(f'{pk}/gates.json')) if os.path.isfile(f'{pk}/gates.json') else {'level': 'UNCHECKED', 'gates': {}}
    M = P['manufacture']
    nodes.append(dict(id=P['sku'], type='product', name=P['name'], family=P['family'], kind=P['kind'], level=G['level'], process=M['process'],
                      price_gbp=P['listing']['price']['amount'], slots=[s['id'] for s in P['slots'] if s['offered']],
                      occasions=P['audience']['occasions'], interests=P['audience'].get('interests', [])))
    for p in P['parents']: edges.append(dict(src=P['sku'], dst=p, rel='instance_of'))
    edges.append(dict(src=P['sku'], dst=f'SUP:{M["supplier"]}', rel='made_by', process=M['process']))
    for r in P['graph'].get('related', []): edges.append(dict(src=P['sku'], dst=r['sku'], rel=r['rel']))
    for i in P['audience'].get('interests', []): edges.append(dict(src=P['sku'], dst=f'INT:{i}', rel='appeals_to'))
    fails = [f'{k} {v["name"]}' for k, v in sorted(G['gates'].items()) if v['status'] == 'FAIL' and k != 'G14']
    rows.append((P['sku'], P['name'], G['level'], M['process'], P['listing']['price']['amount'], fails))
ints = {e['dst'] for e in edges if e['dst'].startswith('INT:')}
nodes += [dict(id=i, type='interest') for i in sorted(ints)]
json.dump(dict(nodes=nodes, edges=edges), open(f'{CAT}/graph.json', 'w'), indent=1)
with open(f'{CAT}/STATUS.md', 'w') as f:
    f.write('# Catalog status (generated by tools/build_graph.py, do not edit)\n\n| SKU | Product | Level | Process | Price | Blocking gates |\n|---|---|---|---|---|---|\n')
    for r in rows: f.write(f'| {r[0]} | {r[1]} | **{r[2]}** | {r[3]} | {"£%.2f" % r[4] if r[4] else "-"} | {"<br>".join(r[5]) or "none"} |\n')
print(len(rows), 'packs,', len(nodes), 'nodes,', len(edges), 'edges')
